declare module '*.gif';
declare module '*.png';
declare module '*.jpg';
declare module '*.eot';
declare module '*.wof';
declare module '*.woff';
declare module '*.woff2';
declare module '*.ttf';
declare module '*.svg';
